CREATE TABLE lists (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE todos (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    complete BOOLEAN NOT NULL DEFAULT FALSE,
    list_id INTEGER NOT NULL REFERENCES lists(id) ON DELETE CASCADE
);